GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRW1tYXIiLCJpYXQiOjE3MDczNDQwMDV9.Dpu6JE9F0mWxs4ogMdhaimp-x5-_hQ6ZnBaIVs-CnLE


###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Emmar"
}